[package]
name = "nasm_proj"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
execute = "0.2.13"
json = "0.12.4"
